### ISSUE TITLE
Missing properties in the `toJS` result object after setting a deep value using `setIn`

### ISSUE THREAD

**Issue by merraysy** [immutable-js/immutable-js#1582]
### What happened

Sometimes (noticed this mainly in big JSON objects e.g. Redux state) when I set a deeply nested value using `Immutable#setIn`, some of the object's properties (in my case they are the siblings of the property that I just set it's value) get deleted, and only the lastly set property is present.

### How to reproduce

Consider having this object deeply nested in a huge JSON:

```
...: {
  items: [
    {
      key1: 'value1'
    }
  ]
}
```

Here is the scenario:
- Create an instance of the JSON with `Immutable#fromJS`
- Set a the value of another key using `Immutable#setIn` e.g. `setIn([...path, 'items', 0, 'key2'], 'value2')`
- Get the new object using `Immutable#toJS`

The result looks like this:

```
...: {
  items: [
    {
      key2: 'value2'
    }
  ]
}
```

I can reproduce here https://codesandbox.io/s/430l0jkln4?expanddevtools=1&view=editor, I simply log the original and result objects in the console. I also did the same on a minimized copy of our JSON and it worked fine. The problem seems to happen only when dealing with large Maps.

**Comment by conartist6** [comment]
Wat.

That's pretty weird.

**Comment by conartist6** [comment]
I've [simplified your repro considerably](https://codesandbox.io/s/4zjv3n06x7). It makes evident the real issue, which is also pretty simple. You have an object with the key `"0"` and you're treating it as an array. This is pretty much fine in normal JS, the only thing you'd be missing is the methods from the array prototype. This is because JS Arrays are fundamentally just objects with keys that are digit strings, along with some perf optimizations and the magic length property. All keys are coerced to strings behind the scenes.

Immutable's types for Lists and Maps are fundamentally different and treat their data in different ways. In particular Map supports types of keys other than strings, and values stored at key `"0"` (a string) are different than values stored at key `0` (a number).

That is why you have a bug. I don't think, unless you disagree, that this is a problem with Immutable itself.

**Comment by merraysy** [comment]
Yes, I agree that it's not related to Immutable in any means. I haven't considered the `stateVisibilities` object as an object, I thought it was an array because those index like keys are confusing especially in Redux Devtools Extension look at that http://take.ms/vJq0a :). Thank you for your time.

**Comment by conartist6** [comment]
Huh, yeah it is extra hard to tell in that view isn't it. I'll keep that in mind for the future myself!
