### ISSUE TITLE
Low conversion performance for toJS

### ISSUE THREAD

**Issue by liangzhuang327** [immutable-js/immutable-js#1599]
### What happened
`let dataSource = Immutable.fromJS(
{peple: {age: 18, preferences:['basketball', 'football']}}}
);
let jsObj = dataSource.toJS()`
I'm using redux, which is very time-consuming for TOJS conversions, especially on some hardware devices. 
For example, sometimes it can take 1 seconds or more.
**I want to know if Imuutable has an API that can use immutable data directly in JavaScript.**

**Comment by conartist6** [comment]
It sure does, that API is the iterable API.  You can read more about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

Also you've included a code example, are you saying that on some devices running that line of code takes 1 second? If not I'm happy to take a look at the actual code which is taking a long time to run to see if there's any obvious problems with it.

**Comment by lukaswelinder** [comment]
@liangzhuang327 I think this may be a duplicate of #1453, which was resolved [here](https://github.com/facebook/immutable-js/commit/0082ff78295fb818eca80e898edbea5af758f9db) and released in `4.0.0-rc.10`. The performance now is almost 60% better than it was before the issue was introduced by `4.0.0-rc.8`.

If you think there is an actual issue, please include steps to reproduce and the version you are using (or, ideally, a repository that demonstrates the issue like in #1453).

That said, it sounds like the issue has more to do with how you are using Immutable.js in combination with your state. From the redux docs on [interoperability challenges w/ Immutable.js](https://redux.js.org/recipes/usingimmutablejs#difficult-to-interoperate-with):

> Note that Immutable.JS objects do have a `toJS()` method, which returns the data as a plain JavaScript data structure, but this method is extremely slow, and using it extensively will negate the performance benefits that Immutable.JS provides

There are a few approaches to working with immutable structures. The first is what @conartist6 mentioned.

Since all immutable structures are iterables, it allows you to do things like this:

```js
const myMap = Map({ /* ... */ });
for(const [key, value] of myMap) {
  /* ... */
}
```

Something that probably better suits your needs is the Immutable.js `Record`. As long as you know the shape of your records ahead of time (and you don't need to support IE8), it allows you to read properties as though it was a regular object instead of having to use `get()` methods.

**Comment by liangzhuang327** [comment]
@lukaswelinder  Thank you very much for your answer，I find I really don't need to convert immutable data into JavaScript objects or arrays
In addition, I would like to ask you another question：
> ```js
>/* in redux */
> const myMap = Map({ test: 'hello' });
> let count = 0
> export function(state = myMap, action){
>switch(action.type){
>  case 'TEST':
>      count++
>      return state.merge({ age: count})
>}
>}
>//dispatch
> dispatch({type: 'Test'})
> ```
As shown above，Whenever I dispatch this Action,redux state will change once. According to the Immutalbe documentation, a new immutable data is generated each time the immutable data is changed, and I wonder where the immutable data generated each time is stored? Will it be put into memory? If so, will it cause the browser to become more and more stuttering?

**Comment by conartist6** [comment]
You can see a bit how Immutable data is stored just by taking a look at an Immutable object. The reference equality property derives from the fact that Immutable data structures are like fancier versions of linked lists.

I might represent a simple singly linked list as three nodes, each storing a value and reference to another node. In shorthand, this would look like:
```
node(3) -> node(2) -> node(1)
```
In this case having a reference to `node(3)` is enough to allow you to get the values `3 -> 2 -> 1`. If the implementation of node forbids changing its contents, that list is immutable. I could add an item to it by making a `node(4)` which points to `node(3)`, and this would not require changing `node(3)`. Thus `node(4)` is a separate list which is `!==` to `node(3)`, even though the rest of the memory for storing items is reused. This is the fundamental pattern which immutable exploits to preserve reference equality.

If you want to get more technical, Immutable isn't actually using singly linked lists, it is using the [Tries](https://en.wikipedia.org/wiki/Trie). I believe the nodes in the tree are stored under vNode when you look at an immutable object. The cost of doing things this way is random access. If you look at Immutable's documentation, you will find that List and Map's `.get()` methods are not defined to take `O(1)` time as they would with a normal array or object. They take `O(log32 n)` time, because Immutable must walk the tree. In general, though, you shouldn't be worried by this. Immutable is quite performant.

**Comment by lukaswelinder** [comment]
@liangzhuang327 A simpler way of describing what @conartist6 said above is that Immutable.js uses object property sharing when creating a new object from a change. I'll try to explain briefly.

Normal property value assignment would be like this:
```js
const a = { age: 1 };
const b = {};
b.age = a.age;
```
In this example, the value is copied in memory. Do this too many times and you start to use more memory.

Property sharing works something like this:
```js
cosnt a = [['age', 1]];
cosnt b = [];
b[0] = a[0];
```
In this example, we just pass a reference to the key/value, so there is less memory used.

For smaller data sets (like your example), Immutable.js might be overkill, but when you have larger sets of data that are frequently changing, it can help reduce memory usage and improve performance.
