### ISSUE TITLE
Correctly type return value of fromJS function with flow

### ISSUE THREAD

**Issue by yantakus** [immutable-js/immutable-js#1665]
Giving the following code:

```javascript
const copy = fromJS([
  {
    points: 1000,
  },
  {
    points: 1001,
  },
  {
    points: 200,
  },
]);

copy.map(() => {});
```

After migrating from immutable.js 3.8 to 4.0.0-rc.12 I get the following error:

> Cannot call `copy.map` because property `map` is missing in `mixed`.

fromJS's return value is typed as mixed now and I can't set it to List.

```javascript
const copy: List<Map<*, *>> = fromJS([
  {
    points: 1000,
  },
  {
    points: 1001,
  },
  {
    points: 200,
  },
]);

copy.map(() => {});
```

gives me:

> Cannot assign `fromJS(...)` to `copy` because `mixed` is incompatible with `List`

**Comment by conartist6** [comment]
Since `fromJS` is a fully dynamic method, it will (almost certainly) never be possible for type systems to understand what it does. Immutable is now letting you know that what you were doing was unsafe from a type perspective, and that you should instead do something that is, verifiably, safe.

In your example it might look like: `List(scores.map(scoreObj => Map(scoreObj)))` where scores is your previous input to `fromJS`.

**Comment by yantakus** [comment]
@conartist6 I see flow can't know the right type `fromJS` returns, so it gives us `mixed`. But I can't understand why I can't override it myself if I know the type, something like this:

```
const copy: List<Map<*, *>> = fromJS([
  {
    points: 1000,
  },
  {
    points: 1001,
  },
  {
    points: 200,
  },
]);

copy.map(() => {});
```
?
