### ISSUE TITLE
Map constructor ignores symbols

### ISSUE THREAD

**Issue by tolmasky** [immutable-js/immutable-js#1731]
`Map({ [MySymbol]: 5 })` generates an empty map despite `Map([[MySymbol, 5]])` generating a single item `Map`. I imagine `Map` uses `Object.keys` on object argument instead of a combination of `Object.keys` and `Object.getOwnPropertySymbols`.

**Comment by balagge** [comment]
This is indeed inconsistent.

Both cases use  `Map()`
https://github.com/immutable-js/immutable-js/blob/751082fd0d392f14f7fa567d5fad6edd8f94bd79/src/Map.js#L42-L55

then this invokes `KeyedCollection()`

https://github.com/immutable-js/immutable-js/blob/751082fd0d392f14f7fa567d5fad6edd8f94bd79/src/Collection.js#L20-L24

then `KeyedSeq()`

https://github.com/immutable-js/immutable-js/blob/751082fd0d392f14f7fa567d5fad6edd8f94bd79/src/Seq.js#L91-L102

then `keyedSeqFromValue()`

https://github.com/immutable-js/immutable-js/blob/751082fd0d392f14f7fa567d5fad6edd8f94bd79/src/Seq.js#L296-L312

Here is the difference between the two cases:
- object argument is handled in `ObjectSeq()`
- array argument is handled in `ArraySeq()`

`ObjectSeq()` uses `Object.keys()` to select keys in the collection, which effectively selects **own, enumerable, string keys** -- Symbol keys are always ignored.

https://github.com/immutable-js/immutable-js/blob/751082fd0d392f14f7fa567d5fad6edd8f94bd79/src/Seq.js#L198-L204

`ArraySeq()` takes the supplied array without filtering, thus uses any key supplied.

Whether the two should both consider Symbol keys is a question. Symbols are not quite supported by immutable js consistently, as can be seen from the documentation https://immutable-js.github.io/immutable-js/docs/#/Map/Map

> Keep in mind, when using JS objects to construct Immutable Maps, that JavaScript Object properties are always strings, [...]

This is obviously false since Symbols have been introduced, so the documentation predates Symbols.

**Comment by balagge** [comment]
However, it can even be argued that the current behavior is intended.

- when constructing from an Array: `Map([[Symbol("foo"), 1]]`, the list of intended keys can be anything by nature, since the constructor arguments are `[key, value]` pairs. This includes Symbols as well as any other objects. Thus the caller is assumed to send exactly the intended keys / values.
- constructing from an Object is quite different. Here there are some interesting questions, whether own or inherited properties should be considered. Also, whether non-enumerable properties should be considered. And, finally, whether Symbol properties should be considered.

Since it is quite frequent that 
- non-enumerable
- inherited
- Symbol
properties are used for some "internal" stuff, it seems quite acceptable to ignore those, as `Object.keys()` does

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties#Detection_Table

To me it seems perfectly valid to say that construction from Object is

**Comment by matt-curtis** [comment]
Both `Map` and `fromJs`, etc., seem to have this flaw. Are there any plans to fix this or at least make it opt-in?
