### ISSUE TITLE
mergeIn inconsistency in merging maps with maps and lists

### ISSUE THREAD

**Issue by GolubevS** [immutable-js/immutable-js#1749]
### What happened

mergeIn inconsistency in merging maps with maps and lists (keys in keyPath do not exist)

### How to reproduce

Merging map with map:

```
import { Map } from 'immutable';

const map = Map({ a: { b: { c: 10 } } });
const newMap = map.mergeIn(['a', 'e'], {c: 20, d: 30});

console.log(newMap.toJS());
```

Result as expected:

{ a: { b: { c: 10 }, e: {c: 20, d: 30}}}

Merging map with list:

```
import { Map } from 'immutable';

const map = Map({ a: { b: [1, 2] } });
const newMap = map.mergeIn(['a', 'e'], [2, 3]);

console.log(newMap.toJS());
```

Expected:

{ a: { b: [1, 2], e: [2, 3] } }

Result: 

Uncaught TypeError: Expected [K, V] tuple: 2

### Update

Issue more general: list cannot be merged with list if key not exists:

```
import { List } from 'immutable';

const myList = List.of(1, 2, [3, [4, 5]]);
const newList = myList.mergeIn([2, 2], [5, 6]);

console.log(newList.toJS());
```
Expected:

[1, 2, [3, [4, 5], [5, 6]]]

Result:

Uncaught TypeError: Expected [K, V] tuple: 5

**Comment by conartist6** [comment]
I think the library is correct here. The problem is that the method specifies that it does a `merge` at the given path. But you're essentially asking to be able to write `merge(undefined, [])`. I would not be inclined to allow that. How do you take nothing and merge the empty array into it? In each of these cases you can do what you want with `setIn` or `updateIn`, and I would suggest that that is what you should do.
