### ISSUE TITLE
.get returns old value, .toJs returns new value

### ISSUE THREAD

**Issue by dor6** [immutable-js/immutable-js#1767]
I get a new immutable map after using set (the value is an object) in the new map object when i use toJS (or just use console.info on it) i get the updated object, when I use get on the value i updated (which is an object btw) I get the old value.

I do the same action twice becuase i have the object twice, once in a list inside a context and once in a function that opens a modal base on this object. the update heppens inside the modal. the list updates just fine but the object inside the modal has the above problem.

My solution was cloning the object using "fromJS(object.toJS())".

My code is in react native, I cant share the code because of confidentiality.

**Comment by bdurrer** [comment]
To be honest, it is more likely that your code has a bug. If you can't share code, create a test case, e.g. on codepen and add it here (or even better, ask on stackoverflow).

**Comment by conartist6** [comment]
Right. Immutable doesn't make everything immutable (such as objects stored in collections). Whatever your store in a data structure is your business. In this case it's a mutable object, so any changes of it will certainly be reflected everywhere there are references to that object. Since that isn't what you want use a `Map` or `Record` to store that data and you'll be on your way.

Could you please close this ticket?
