### ISSUE TITLE
Range() defaulting to infinite is easy to misuse and end up with a silent infinite loop

### ISSUE THREAD

**Issue by sergueif** [immutable-js/immutable-js#1801]
Hey, big fan here, long time user, first time caller. First, let me say, sharp tools can be a pleasure to use, but I also believe workplace injuries should be reported. 

### what happened
Someone on my team wrote an innocent-looking component with the help of `Range()`:
```
const SomeComponent = ({min, max}) => {
  return <div>
    <!-- more html -->
    {Range(min, max).map(num => <option value={num}>{num}</option>)}
  </div>
}
```
called it some place and moved on with their day. 

Later, in a different context, rendering the above component resulted in an infinite loop that took over an hour to find. The cause, of course is that Range(undefined, undefined) or without arguments is infinite. Seems it would be safer if getting an infinite range required being more explicit.

I anticipate this may get shut down, cause like "read the docs, be careful, use typescript" and what not, but has anyone else been burned by this? Am I the first to get infinite Range unintentionally?

**Comment by jdeniau** [comment]
Hi,

It is indeed in the API since Range has been released. I'm not confident enough to change that in `4.0`, but should be a discussion for 5.0.

My point of view is that we should avoid infinite loop because it's probably more a bug that a feature.

A possible way to achieve that is in fact to force this behavior:

```js
Range(0, Infinity)
```

and either force both `start` and `end`, or force the first parameter to be defined:
```js
Range(2, 5); // [2, 3, 4, 4]
Range(5); // [0, 1, 2, 3, 4]
```
This comportment will break the following case too:
```js
Range(10) // [ 10, 11, 12, 13, ... ]
```

We may want to deprecate undefined `end` parameter and explain this.

**Comment by sergueif** [comment]
That's great! Looking forward to 5.0

**Comment by jdeniau** [comment]
Fixed in 5.x (in meta for now, but will be released soon)
