### ISSUE TITLE
Urgent: Package Installation Reveals Multiple Vulnerabilities

### ISSUE THREAD

**Issue by RahatFatimah** [immutable-js/immutable-js#1946]
Dear Maintainer Team,

I hope this message finds you in good health. I am writing to inform you about a security issue detected following the installation of our latest package. I performed a vulnerability scan on the lock file using the Vulert Abom tool, and the results show an unsettling 24 vulnerable dependencies.

The potential threat that these vulnerabilities pose to the security of the entire project has led me to contemplate whether this situation falls under responsible disclosure.

You can refer to the following link for the scan report of the package-lock file: https://vulert.com/vuln-scan/list/cd8146fc-b8c4-412a-aa88-97d1206fbbbb

It is critically important that we take swift action to rectify these vulnerabilities and ensure the project's security. If there's any additional information you require, please feel free to ask.

You may find the scanned lock file at this link: https://github.com/immutable-js/immutable-js/blob/main/package-lock.json

Thank you for your prompt attention to this matter.

Best regards,

**Comment by jdeniau** [comment]
Dear automated bot,

Maintaining an open-source package takes a lot of time. Please don't use github for your SEO.

If you are really interested in the security of this package, do open PR instead of linking your website.

![image](https://github.com/immutable-js/immutable-js/assets/1398469/f4783098-f69e-40ae-807b-5b0c11addbaf)

![image](https://github.com/immutable-js/immutable-js/assets/1398469/0415ca21-2655-40dc-b732-62175742d811)
