### ISSUE TITLE
List.has() should do the same as List.includes()

### ISSUE THREAD

**Issue by Dagur** [immutable-js/immutable-js#1999]
### What happened

I used List.has() in a program and it caused a bug. The immutable documentation doesn't explain what it does (I'm curious to know). What I should have used was List.includes() (or List.contains()).

### How to reproduce

```
const test = List([1,2,3]);
console.log(test.has(2), test.includes(2));
```

My suggestion is to either make List.has work exactly like List.includes or print a warning in the console.

**Comment by jdeniau** [comment]
This is weird because this is the implementation of KeyedCollection

You can do this

```ts
const l = List (['a', 'b']).
l.has(1) // true, value is b
l.has(2) // false, no second key
```

The code can be found here
https://github.com/immutable-js/immutable-js/blob/main/src%2FCollectionImpl.js#L383-L385

At first sight, this seems really weird (and that's probably why it's not documented).

I did not check, but the Set.has method do probably why you want. (you might not want to use a Set, but it's to point that Set, which is an unidexed collection, does probably implement this, which makes it weirder on List)

**Comment by jdeniau** [comment]
After re-reading this, I checked out the documentation, and it is, in fact, documented: https://immutable-js.com/docs/v4.3.6/List/#has()

> True if a key exists within this [Collection](https://immutable-js.com/docs/v4.3.6/Collection), using [Immutable.is](https://immutable-js.com/docs/v4.3.6/is()) to determine equality
> 
> has(key: number): boolean

This is consistent with `Map` implementation, and I don't want to break the API here.

Closing as won't fix.

**Comment by Dagur** [comment]
Can I then suggest that the documentation is changed to say *index* instead of *key*?
